## Exploration du dataframe

In [ ]:
import pandas as pd
from pathlib import Path

# Chemin robuste : notebook dans /notebooks
DATA_PATH = Path("data/raw/movie_metadata.csv")

{}

In [ ]:
df = pd.read_csv('DATA_PATH')

In [ ]:
df.head()

,color,movie_title,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,Avatar,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000.0
1,Color,Pirates of the Caribbean: At World's End,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0.0
2,Color,Spectre,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000.0
3,Color,The Dark Knight Rises,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000.0
4,Color,John Carter,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000.0

In [ ]:
df.shape

(5043, 28)

In [ ]:
df.isna().sum()

color                         17
movie_title                    1
director_name                105
num_critic_for_reviews        50
duration                      16
director_facebook_likes      105
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         8
gross                        884
genres                         1
actor_1_name                   8
num_voted_users                1
cast_total_facebook_likes      1
actor_3_name                  23
facenumber_in_poster          14
plot_keywords                153
movie_imdb_link                1
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     1
aspect_ratio                 329
movie_facebook_likes           1
dtype: int64

### On vérifie les durées en dessous de 60 minutes

In [ ]:
df_check = df.loc[df['duration'] < 60]

In [ ]:
df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

/tmp/ipython-input-2791782956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

In [ ]:
df_check[['movie_title', 'movie_imdb_link']]

,movie_title,movie_imdb_link
395,Hannibal,http://www.imdb.com/title/tt2243973
524,Constantine,http://www.imdb.com/title/tt3489184
530,Life,http://www.imdb.com/title/tt0874936
580,Sleepy Hollow,http://www.imdb.com/title/tt2647544
631,Last Man Standing,http://www.imdb.com/title/tt1828327
...,...,...
4844,McHale's Navy,http://www.imdb.com/title/tt0055689
4862,The Honeymooners,http://www.imdb.com/title/tt0042114
5018,The Call of Cthulhu,http://www.imdb.com/title/tt0478988
5026,Daredevil,http://www.imdb.com/title/tt3322312
5032,Alpha and Omega 4: The Legend of the Saw Tooth...,http://www.imdb.com/title/tt4061848

In [ ]:
to_del = [279,404,459,479,537,543,593,645,757,816,826,833,857,962,1023,1133,1175,1265,1404, 620,1664,1736,1802,1818,1842\
          ,1947,1972,2075,2191,2241,2257,2303,2342,2370,2412,2594,2609,2824,2828,2952,3084,3174,3207,3303,3329,3481,3490,\
          3579,3623,3661,3807,3847,3951,3982,3989,4015,4079,4115,4281,4327,4482,4634,4803,4819,4869,5039]

### On vérifie les durées au dessus de 3 heures

In [ ]:
df_check = df.loc[df['duration'] > 240]

In [ ]:
df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

/tmp/ipython-input-2791782956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

In [ ]:
df_check[['movie_title', 'movie_imdb_link']]

                       movie_title                      movie_imdb_link
860             Gods and Generals   http://www.imdb.com/title/tt0279111
1113                Heaven's Gate   http://www.imdb.com/title/tt0080855
1129                    Cleopatra   http://www.imdb.com/title/tt0056937
1457          Blood In, Blood Out   http://www.imdb.com/title/tt0106469
1524               Apocalypse Now   http://www.imdb.com/title/tt0078788
1661                      Trapped   http://www.imdb.com/title/tt3561180
1665  Once Upon a Time in America   http://www.imdb.com/title/tt0087843
1923                   Gettysburg   http://www.imdb.com/title/tt0107007
2393                       Carlos   http://www.imdb.com/title/tt1321865
2485      Arn: The Knight Templar   http://www.imdb.com/title/tt0837106
2648                  The Company   http://www.imdb.com/title/tt0488352
2882                     Das Boot   http://www.imdb.com/title/tt0082096
3213     The Legend of Suriyothai   http://www.imdb.com/title/tt0290879

In [ ]:
to_del2 = [1710, 2466, 2727]

### On vérifie les durées nulles

In [ ]:
df_check = df.loc[df['duration'].isnull()]

In [ ]:
df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

/tmp/ipython-input-2791782956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

In [ ]:
df_check[['movie_title', 'movie_imdb_link']]

,movie_title,movie_imdb_link
196,Harry Potter and the Deathly Hallows: Part II,http://www.imdb.com/title/tt1680310
203,Harry Potter and the Deathly Hallows: Part I,http://www.imdb.com/title/tt1571403
1465,Black Water Transit,http://www.imdb.com/title/tt0490087
3496,War & Peace,http://www.imdb.com/title/tt3910804
3697,Should've Been Romeo,http://www.imdb.com/title/tt1717210
3716,Barfi,http://www.imdb.com/title/tt3099638
4146,Hum To Mohabbat Karega,http://www.imdb.com/title/tt0249588
4227,N-Secure,http://www.imdb.com/title/tt1289419
4232,Dil Jo Bhi Kahey...,http://www.imdb.com/title/tt0442764
4340,Wolf Creek,http://www.imdb.com/title/tt4460878
4427,Karachi se Lahore,http://www.imdb.com/title/tt4590482
4503,Destiny,http://www.imdb.com/title/tt2983582
4735,Romantic Schemer,http://www.imdb.com/title/tt4607906
4768,The Naked Ape,http://www.imdb.com/title/tt0381053
5024,Star Wars: Episode VII - The Force Awakens,http://www.imdb.com/title/tt5289954
5025,NaN,nan

In [ ]:
to_del3 = [3604, 4517, 4690]

In [ ]:
# Suppression lignes inutiles
df = df.drop(to_del + to_del2 + to_del3)

### On remplace les durées manquantes

In [ ]:
df_replace = df.loc[df['duration'].isnull()]
df_replace

,color,movie_title,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
196,Color,Harry Potter and the Deathly Hallows: Part II,Matt Birch,1.0,NaN,0.0,159.0,Dave Legeno,10000.0,NaN,...,2.0,English,UK,NaN,NaN,2011.0,570.0,7.5,NaN,40.0
203,Color,Harry Potter and the Deathly Hallows: Part I,Matt Birch,4.0,NaN,0.0,1000.0,Toby Jones,10000.0,NaN,...,2.0,English,UK,NaN,NaN,2010.0,2000.0,6.4,NaN,25.0
1465,Color,Black Water Transit,Tony Kaye,NaN,NaN,194.0,816.0,Aisha Tyler,970.0,NaN,...,NaN,English,USA,NaN,23000000.0,2009.0,856.0,7.2,NaN,26.0
3496,Color,War & Peace,NaN,10.0,NaN,NaN,502.0,Tuppence Middleton,1000.0,NaN,...,44.0,English,UK,TV-14,NaN,NaN,888.0,8.2,16.00,11000.0
3697,Color,Should've Been Romeo,Marc Bennett,2.0,NaN,3.0,723.0,Natasha Henstridge,975.0,NaN,...,2.0,English,USA,NaN,5000000.0,2012.0,900.0,6.7,NaN,35.0
3716,Color,Barfi,Shekar,1.0,NaN,0.0,0.0,Diganth,5.0,NaN,...,1.0,Kannada,India,NaN,NaN,2013.0,0.0,7.1,NaN,2.0
4146,Color,Hum To Mohabbat Karega,Kundan Shah,1.0,NaN,4.0,72.0,Bobby Deol,353.0,NaN,...,1.0,Hindi,India,NaN,NaN,2000.0,89.0,2.8,NaN,10.0
4227,Color,N-Secure,David M. Matthews,5.0,NaN,8.0,394.0,Lamman Rucker,713.0,2592808.0,...,15.0,English,USA,R,NaN,2010.0,607.0,3.5,2.35,588.0
4232,Color,Dil Jo Bhi Kahey...,Romesh Sharma,4.0,NaN,0.0,45.0,Revathy,421.0,129319.0,...,4.0,English,India,NaN,70000000.0,2005.0,96.0,5.1,NaN,9.0
4340,Color,Wolf Creek,NaN,2.0,NaN,NaN,206.0,John Jarratt,511.0,NaN,...,6.0,English,Australia,NaN,NaN,NaN,457.0,7.1,2.00,954.0
4427,Color,Karachi se Lahore,Wajahat Rauf,6.0,NaN,3.0,4.0,Ayesha Omar,7.0,NaN,...,15.0,Urdu,Pakistan,NaN,1000000.0,2015.0,5.0,7.0,NaN,259.0
4503,Color,Destiny,Joseph Kosinski,4.0,NaN,364.0,567.0,Lauren Cohan,22000.0,NaN,...,11.0,English,USA,NaN,NaN,2014.0,4000.0,8.1,NaN,1000.0
4735,Color,Romantic Schemer,Valentine,NaN,NaN,0.0,NaN,Valentine,17.0,NaN,...,NaN,English,USA,PG-13,125000.0,2015.0,0.0,5.1,NaN,0.0
4768,Color,The Naked Ape,Daniel Mellitz,NaN,NaN,0.0,15.0,Chelse Swain,1000.0,NaN,...,3.0,English,USA,NaN,NaN,2006.0,36.0,4.7,NaN,2.0
5024,Color,Star Wars: Episode VII - The Force Awakens,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0.0
5025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.at[4, 'duration'] = 138
df.at[199, 'duration'] = 130
df.at[206, 'duration'] = 146
df.at[1510, 'duration'] = 100
df.at[3815, 'duration'] = 120
df.at[3834, 'duration'] = 105
df.at[4299, 'duration'] = 153
df.at[4392, 'duration'] = 105
df.at[4397, 'duration'] = 144
df.at[4609, 'duration'] = 143
df.at[4948, 'duration'] = 84
df.at[4989, 'duration'] = 100

### On vérifie les dates de sorties nulles

In [ ]:
df_check = df.loc[df['title_year'].isnull()]

In [ ]:
df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

/tmp/ipython-input-2791782956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

In [ ]:
df_check[['movie_title', 'movie_imdb_link']]

,movie_title,movie_imdb_link
174,Miami Vice,http://www.imdb.com/title/tt0086759
256,The A-Team,http://www.imdb.com/title/tt0084967
395,Hannibal,http://www.imdb.com/title/tt2243973
524,Constantine,http://www.imdb.com/title/tt3489184
530,Life,http://www.imdb.com/title/tt0874936
...,...,...
4862,The Honeymooners,http://www.imdb.com/title/tt0042114
5024,Star Wars: Episode VII - The Force Awakens,http://www.imdb.com/title/tt5289954
5025,NaN,nan
5026,Daredevil,http://www.imdb.com/title/tt3322312
5029,Unforgettable,http://www.imdb.com/title/tt1842530

In [ ]:
to_del4 = [177,260,685,994,1007,1035,1346,1444,1499,1620,1659,2143,2459,2552,2702,2765,2775,2870,3376,3397,3419,\
           3507,3509,3650,3800,3871,3881,3900,4087,4113,4119,4249,4288,4304,4460,4467,4798]

In [ ]:
# Suppression des lignes inutiles

df = df.drop(to_del4)

### On remplace les languages manquants

In [ ]:
df_check = df.loc[df['language'].isnull()]

In [ ]:
df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

/tmp/ipython-input-2791782956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_check['movie_imdb_link'] = df_check['movie_imdb_link'].map(lambda x: str(x)[:35])

In [ ]:
df_check[['movie_title', 'movie_imdb_link']]

,movie_title,movie_imdb_link
2812,Quest for Fire,http://www.imdb.com/title/tt0082484
2994,September Dawn,http://www.imdb.com/title/tt0473700
3751,Silent Movie,http://www.imdb.com/title/tt0075222
3810,Samsara,http://www.imdb.com/title/tt0770802
3978,Love's Abiding Joy,http://www.imdb.com/title/tt0785025
4996,Intolerance: Love's Struggle Throughout the Ages,http://www.imdb.com/title/tt0006864
5002,The Big Parade,http://www.imdb.com/title/tt0015624
5013,Over the Hill to the Poorhouse,http://www.imdb.com/title/tt0011549
5024,Star Wars: Episode VII - The Force Awakens,http://www.imdb.com/title/tt5289954
5025,NaN,nan
5029,Unforgettable,http://www.imdb.com/title/tt1842530
5032,Alpha and Omega 4: The Legend of the Saw Tooth...,http://www.imdb.com/title/tt4061848
5038,Kickboxer: Vengeance,http://www.imdb.com/title/tt3082898
5040,A Fine Step,http://www.imdb.com/title/tt1604100

In [ ]:
df.at[4, 'language'] = 'English'
df.at[3086, 'language'] = 'English'
df.at[3539, 'language'] = 'English'
df.at[3869, 'language'] = 'English'
df.at[4110, 'language'] = 'English'
df.at[4409, 'language'] = 'English'
df.at[4630, 'language'] = 'English'
df.at[4810, 'language'] = 'English'
df.at[4885, 'language'] = 'English'
df.at[4958, 'language'] = 'English'

### Les pays et couleurs manquants ont été fait sur le excel

## Check

In [ ]:
df.isna().sum()

color                         16
movie_title                    1
director_name                104
num_critic_for_reviews        49
duration                      16
director_facebook_likes      104
actor_3_facebook_likes        21
actor_2_name                  12
actor_1_facebook_likes         7
gross                        871
genres                         1
actor_1_name                   7
num_voted_users                1
cast_total_facebook_likes      1
actor_3_name                  21
facenumber_in_poster          13
plot_keywords                149
movie_imdb_link                1
num_user_for_reviews          20
language                      14
country                        4
content_rating               300
budget                       484
title_year                   107
actor_2_facebook_likes        12
imdb_score                     1
aspect_ratio                 321
movie_facebook_likes           1
dtype: int64

In [ ]:
OUT_PATH = Path("../data/clean/movie_clean.csv")
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(OUT_PATH, index=False)
print(f"Fichier sauvegardé : {OUT_PATH.resolve()}")

In [ ]:
df.shape

In [ ]:
df.duplicated().sum()

np.int64(42)

In [ ]:
5043 - 4934

109